[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
version = '0.0.1'
name = 'geocoding_frame'
dependencies = ['geocoding_frame @ git+https://github.com/iph-dtc/geocoding_frame.git',]
