[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
version = 'v1.0.0'
name = 'geocoding_frame'
dependencies = ['geocoding_frame @ git+ssh://git@github.com/iph-dtc/geocoding_frame.git',]
